** Fukagyaku Replace 

Wake in loneliness!! Loneliness!!
Falling inside your story
Walking after you!! After you!!
I will share my time

迷い込んだ世界で
僕の影と重なって 今
I can't go back

決定的「僕」の証明は
時代を今超えて 物語る
And now I will be the brand new age yeah from this day!!

I will save myself
And the time is now!!

Kill my weakness!! Weakness!!
必ず 越えて 泣いて 去って
And I stay alive!! Stay alive!!
最後を信じたくはなくて!
Kill my weakness!! Weakness!!
いつか気付いたとしても
I will prove myself that I have lived today
Starting now!!

変わり果てた 景色で
自らの運命知って また
We'll carry on!!
絶対的「僕」の存在は
形を変え今響き渡る
And now I will be the brand new age yeah from this day!!

Wake in loneliness!! Loneliness!!
いつかは 絶えて 消して 散って
Walking after you! After you!
どうなったって悔いはなくて
Wake in loneliness!! Loneliness!!
もう理由なんか無くていいの!
I will prove myself that I have lived today
Starting now!!

I don't know why
But you saved me
Wherever you came from
Feel you inside me
Maybe it's too late
I've decided to live only for you (live only for you)
I will follow you! Follow you!
If I die for you
I will lead you! Lead you!
For the brighter future
Never fade away! Fade away!
Keep you close to me! Close to me!
(Close to me! Close to me!)
(Close to me! Close to me!)

何年経っても待っても
失くさぬ様に抱きかかえた
ずっと哀しくて虚しくて
もう先なんてないから!
Kill my weakness!! Weakness!!
必ず 越えて 泣いて 去って
And I stay alive!! Stay alive!!
最後を信じたくはなくて!
Kill my weakness!! Weakness!!
いつか気付いたとしても
I will prove myself that I have lived today
Starting now!!
